### ISSUE TITLE
List and ordered list doesn't render in the kanban board

### ISSUE THREAD

**Issue by JPR75** [joplin/plugin-yesyoukan#1]
Hi,

Thank you for this excellent plugin.
It seems that list and ordered list does not appear in the kanban board screen:

![YesYouKan](https://github.com/user-attachments/assets/f1803571-abe5-4b6f-a67f-3f7cd95fd440)

---

Joplin 3.0.15 (Windows 10)
YesYouKan: 1.0.3

**Comment by laurent22** [comment]
Good point, I'll look into this!
