### ISSUE TITLE
Clicking Checkbox affects multiple cards

### ISSUE THREAD

**Issue by bsavant** [joplin/plugin-yesyoukan#10]
Toggling a checkbox on a note can also toggle the checkbox on additional cards on the board.

https://github.com/user-attachments/assets/5500d0c1-8ca7-4d83-a8d9-3e7b224711ee

**Comment by laurent22** [comment]
I knew there could be this bug! But somehow couldn't replicate it so I thought maybe not... but looks it can happen. Thanks for providing the video, I'll take a look
