### ISSUE TITLE
Checklists dont save the checkmarks

### ISSUE THREAD

**Issue by Pedro-Beirao** [joplin/plugin-yesyoukan#12]
I add a checklist like shown in the image, but the checkmarks dont get saved when I switch to another note. If i double click to edit the text, the markdown checkmarks are not checked (they all appear as "- [ ]" without the "x")

![Screenshot 2024-11-19 at 17 40 10](https://github.com/user-attachments/assets/8284074f-1a4e-4137-a52c-d99de2f6597c)

**Comment by laurent22** [comment]
I made a few checkbox related fixed recently. Which version of the plugin is this?

**Comment by Pedro-Beirao** [comment]
v1.0.9

Ive also just updated to v1.0.10, and it still happens

**Comment by laurent22** [comment]
I still can't replicate this. Would you mind checking the console to see if there's any error when you click on a checkbox? https://joplinapp.org

Or alternatively please provide the complete Markdown content of the note to replicate the bug

**Comment by Pedro-Beirao** [comment]
Oh it works now. I updated to the Joplin 3.2.3 yesterday, and it is fixed now

Ive just tried on 3.2.1 (min required version for this plugin) and it is bugged there

**Comment by laurent22** [comment]
Right, it indeed requires the latest pre release. Glad it's working now!
