### ISSUE TITLE
Improving

### ISSUE THREAD

**Issue by davidnurdin** [joplin/plugin-yesyoukan#6]
Do you think it's possible to auto hide the panel at the left ?

![image](https://github.com/user-attachments/assets/54107643-1ab7-49f5-a2fa-5c84de1e6693)

Thanks

**Comment by thoovee** [comment]
Seconding this, or even if it could be resized. This would be the only thing I need for it to be PERFECT.

**Comment by laurent22** [comment]
I wish, but it requires a change to the main app. We'll investigate and see if that can be done

**Comment by laurent22** [comment]
Implemented in v1.0.7
